#!/usr/bin/env python3
"""
build_top2_h5.py

Create a new HDF5 file like the previous one, except:
- It stores ONLY the top-2 modes and weights, generated by your CNN.
- The parameters' index 1 (0-based) is fixed to a constant for every waveguide.

If no model is provided, you can fallback to copying the first two columns from
existing 'modes' and 'weights' datasets.

Usage examples:
---------------
# Using a model (recommended)
python build_top2_h5.py \
  --in_h5 train_test_split.h5 \
  --out_h5 train_top2_pred.h5 \
  --model_module my_models.net4 \
  --model_class Net4_Top2 \
  --checkpoint path/to/model.pth \
  --fixed_param1 0.400 \
  --batch_size 512

# Fallback to existing datasets (no model)
python build_top2_h5.py \
  --in_h5 train_test_split.h5 \
  --out_h5 train_top2_pred.h5 \
  --fixed_param1 0.400 \
  --fallback_from_existing

Notes:
------
- Model must accept tensors: waveguide [B,1,H,W] (or [B,H,W], we will expand)
  and params [B,P], and return either:
    * [B,4]: (mode0, mode1, weight0, weight1), or
    * [B,2]: (mode0, weight0). If you also pass --two_pass with --second_head
      we call the model twice with a head selector kwarg to produce the two pairs.
- No normalization is applied unless you add it (see TODO hooks).
- Attributes about provenance are saved under /meta attrs in the output file.
"""

from only_mode_only_weight_v3 import No_normal_modewieght_net
from typing import Tuple
import argparse
import importlib
import os
from typing import Optional, Tuple

import h5py
import numpy as np
import torch
from torch import nn
from tqdm import tqdm


class CombinedModeWeightNet(nn.Module):
    def __init__(self, mode_model, weight_model):
        super().__init__()
        self.mode_model = mode_model
        self.weight_model = weight_model

    def forward(self, x_img, x_cond):
        mode = self.mode_model(x_img, x_cond)   # [B, 1]
        weight = self.weight_model(x_img, x_cond)  # [B, 1]
        return torch.cat((mode, weight), dim=1)   # [B, 2]


def quarter(matrix):
    return matrix[:32, :32]


device = 'cuda' if torch.cuda.is_available() else 'cpu'

mode0_model = No_normal_modewieght_net().to(device)
weight0_model = No_normal_modewieght_net().to(device)

mode0_model.load_state_dict(torch.load(
    'models/only_first_mode_no_normalization_with_less_dropout.pth', map_location=torch.device(device)))
weight0_model.load_state_dict(torch.load(
    'models/only_first_weight_no_normalization_with_less_dropout_100.pth', map_location=torch.device(device)))

cnn = CombinedModeWeightNet(mode0_model, weight0_model).to(device)
cnn.eval()
#!/usr/bin/env python3
"""
build_cnn_top1_h5.py

Create a new HDF5 file with the SAME keys as the original:
  weight_train, pattern_train, neff_train, params_train,
  weight_test,  pattern_test,  neff_test,  params_test

Differences in the NEW file:
- pattern_* : quartered via your `quarter()` function
- params_*  : identical to input except params[:, 1] is set to a fixed constant
- neff_*, weight_* : SINGLE values per sample, predicted by your `cnn`
  using (quartered_pattern, RAW params) as inputs

Assumptions:
- You already have a Python module that exposes `cnn` and `quarter`.
  Provide it via --context_module (and optionally --cnn_name / --quarter_name).
- cnn forward signature (batched):
      out = cnn(pattern_quartered_tensor, params_tensor)  # -> [B, 2]
  where out[:, 0] = top mode (neff), out[:, 1] = top weight.

Usage:
  python build_cnn_top1_h5.py \
    --in_h5 train_test_split.h5 \
    --out_h5 new_top1_cnn.h5 \
    --fixed_param1 0.400 \
    --context_module my_runtime_objects \
    --cnn_name cnn \
    --quarter_name quarter \
    --batch_size 512 \
    --overwrite
"""


def import_runtime(context_module: str, cnn_name: str, quarter_name: str) -> Tuple[nn.Module, callable]:
    mod = importlib.import_module(context_module)
    cnn = getattr(mod, cnn_name)
    quarter = getattr(mod, quarter_name)
    if not isinstance(cnn, nn.Module):
        raise TypeError(
            f"{cnn_name} from {context_module} is not a torch.nn.Module")
    return cnn, quarter


@torch.no_grad()
def batched_predict(
    cnn: nn.Module,
    quarter_fn,
    patterns: np.ndarray,
    params: np.ndarray,
    batch_size: int,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Returns:
      pattern_q_all : np.ndarray, quartered patterns (same dtype as input, stacked)
      neff_all      : np.ndarray, shape [N], float32
      weight_all    : np.ndarray, shape [N], float32
    """
    device = next(cnn.parameters()).device
    N = patterns.shape[0]

    # We build output containers lazily to match quarter()'s output shape
    pattern_q_all = None
    neff_all = np.zeros((N,), dtype=np.float32)
    weight_all = np.zeros((N,), dtype=np.float32)

    for s in tqdm(range(0, N, batch_size), desc="Quarter+Predict"):
        e = min(s + batch_size, N)
        patt_np = patterns[s:e]        # [B, ...]
        params_np = params[s:e]        # [B, P]

        # Apply quarter() to each sample. quarter() is expected to accept a single pattern array.
        patt_q_list = [quarter_fn(p) for p in patt_np]
        patt_q = np.stack(patt_q_list, axis=0)

        # Initialize pattern_q_all lazily with the correct shape/dtype
        if pattern_q_all is None:
            pattern_q_all = np.zeros(
                (N, *patt_q.shape[1:]), dtype=patt_q.dtype)

        # Move inputs to torch
        patt_q_t = torch.from_numpy(patt_q).float().to(
            device, non_blocking=True)
        # Add channel if needed to be [B,1,H,W]
        if patt_q_t.ndim == 3:
            patt_q_t = patt_q_t.unsqueeze(1)
        elif patt_q_t.ndim == 4:
            # assume already [B, C, H, W]; ok
            pass
        else:
            raise ValueError(
                f"Unexpected quartered pattern dims: {tuple(patt_q_t.shape)}")

        params_t = torch.from_numpy(params_np).float().to(
            device, non_blocking=True)

        # Forward: expects [B,2] = [neff, weight]
        out = cnn(patt_q_t, params_t)
        if isinstance(out, (tuple, list)):
            out = out[0]
        if out.ndim != 2 or out.shape[1] != 2:
            raise RuntimeError(
                f"cnn must return [B,2]; got {tuple(out.shape)}")

        # Save outputs
        out_np = out.detach().cpu().numpy().astype(np.float32)
        neff_all[s:e] = out_np[:, 0]
        weight_all[s:e] = out_np[:, 1]
        pattern_q_all[s:e] = patt_q

    return pattern_q_all, neff_all, weight_all


def copy_split(fin, fout, split: str, fixed_param1: float, batch_size: int, cnn: nn.Module, quarter_fn):
    """
    Processes one split: 'train' or 'test'.
    Reads pattern_{split}, params_{split}; writes:
      pattern_{split} (quartered)
      params_{split}  (with [:,1] fixed)
      neff_{split}    (shape [N], float32)
      weight_{split}  (shape [N], float32)
    """
    patt_key = f"pattern_{split}"
    params_key = f"params_{split}"
    neff_key = f"neff_{split}"
    weight_key = f"weight_{split}"

    if patt_key not in fin or params_key not in fin:
        raise KeyError(f"Missing required datasets for split='{split}'")

    patt_ds = fin[patt_key]      # [N, H, W] or [N, 1, H, W]
    params_ds = fin[params_key]  # [N, P]
    N = patt_ds.shape[0]

    # Load all params (we need RAW for CNN; and we also write a modified copy)
    params_np = params_ds[...].astype(np.float32)
    if params_np.shape[1] < 2:
        raise ValueError("params must have at least 2 columns to set index 1")

    # Load patterns in streaming chunks to control memory
    # We'll pull patterns by batch inside batched_predict
    # But many h5py backends prefer contiguous slicing; we'll read large contiguous blocks.
    # Simpler: read all patterns at once (common case). If memory is a concern, you can chunk this.
    patt_np = patt_ds[...]

    # Predict from RAW params (as requested)
    pattern_q_all, neff_all, weight_all = batched_predict(
        cnn=cnn,
        quarter_fn=quarter_fn,
        patterns=patt_np,
        params=params_np,
        batch_size=batch_size,
    )

    # Write quartered patterns
    fout.create_dataset(patt_key, data=pattern_q_all, compression="gzip")

    # Write fixed params copy
    # Write params copy with per-sample computed value:
    # params_out[:, 1] = FIXED_PARAM1 / params_raw[:, 0]
    params_out = params_np.copy()
    den = params_np[:, 0].astype(np.float32)

    # Guard for zeros in the 0th param
    eps = np.finfo(np.float32).eps
    num_zeros = int((den == 0.0).sum())
    if num_zeros > 0:
        print(
            f"[WARN] {num_zeros} samples have params[:,0] == 0. Replacing with eps to avoid divide-by-zero.")

    safe_den = np.where(den != 0.0, den, eps).astype(np.float32)
    params_out[:, 1] = float(fixed_param1) / safe_den  # per-sample value

    fout.create_dataset(params_key, data=params_out, compression="gzip")

    # Write single-value neff/weight
    fout.create_dataset(neff_key, data=neff_all,
                        dtype="f4", compression="gzip")
    fout.create_dataset(weight_key, data=weight_all,
                        dtype="f4", compression="gzip")


# =========================
# CONFIG: edit in VS Code
# =========================
IN_H5 = "train_test_split.h5"
OUT_H5 = "new_top1_cnn.h5"
FIXED_PARAM1 = 400 * 1e-9          # <-- your new value for params[:, 1]
BATCH_SIZE = 512
OVERWRITE = True

# Option A: import cnn/quarter from a module
# set True if cnn & quarter are already in this script's globals
USE_LOCAL_OBJECTS = False
CONTEXT_MODULE = "my_runtime_objects"
CNN_NAME = "cnn"
QUARTER_NAME = "quarter"


def main_vscode():
    """
    Run entirely from in-file config (VS Code).
    """
    import os
    import h5py
    import torch

    # safety: overwrite guard
    if os.path.exists(OUT_H5) and not OVERWRITE:
        raise FileExistsError(
            f"{OUT_H5} exists. Set OVERWRITE=True or change OUT_H5.")

    # get cnn + quarter
    if USE_LOCAL_OBJECTS:
        # Expect `cnn` (nn.Module) and `quarter` (callable) to already be defined in this file's globals
        try:
            cnn_obj = globals()["cnn"]
            quarter_fn = globals()["quarter"]
        except KeyError:
            raise RuntimeError(
                "USE_LOCAL_OBJECTS=True but `cnn` and/or `quarter` not found in globals().")
    else:
        cnn_obj, quarter_fn = import_runtime(
            CONTEXT_MODULE, CNN_NAME, QUARTER_NAME)

    cnn_obj.eval()
    # touch params to ensure device is initialized
    _ = next(cnn_obj.parameters())
    print(
        f"Using cnn from: {'locals' if USE_LOCAL_OBJECTS else CONTEXT_MODULE}")

    with h5py.File(IN_H5, "r") as fin, h5py.File(OUT_H5, "w") as fout:
        # train split
        copy_split(fin, fout, "train", FIXED_PARAM1,
                   BATCH_SIZE, cnn_obj, quarter_fn)
        # test split
        copy_split(fin, fout, "test",  FIXED_PARAM1,
                   BATCH_SIZE, cnn_obj, quarter_fn)

        # provenance
        meta = fout.create_group("meta")
        meta.attrs["source_h5"] = os.path.abspath(IN_H5)
        meta.attrs["fixed_param1"] = float(FIXED_PARAM1)
        meta.attrs["batch_size"] = int(BATCH_SIZE)
        meta.attrs["overwrite"] = bool(OVERWRITE)
        meta.attrs["context_source"] = "locals" if USE_LOCAL_OBJECTS else CONTEXT_MODULE
        meta.attrs["cnn_name"] = CNN_NAME
        meta.attrs["quarter_name"] = QUARTER_NAME

    print(f"Done. Wrote: {OUT_H5}")


if __name__ == "__main__":
    # Run directly from the editor with your CONFIG above
    main_vscode()
